server:
  port: 8998
###服务别名----服务注册到注册中心名称 
#spring:
#  application:
#    name: app-soft-platform-center
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.0.110:1521:zhlis
#    username: bslis
#    password: bsoft
#    druid:
#      # 初始连接数
#      initialSize: 5
#      # 最小连接池数量
#      minIdle: 10
#      # 最大连接池数量
#      maxActive: 200
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      maxEvictableIdleTimeMillis: 900000
#      # 配置检测连接是否有效
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      webStatFilter:
#        enabled: true
#      statViewServlet:
#        enabled: true
#        # 设置白名单，不填则允许所有访问
#        allow:
#        url-pattern: /druid/*
#        # 控制台管理用户名和密码
#        login-username:
#        login-password:
#      filter:
#        stat:
#          enabled: true
#          # 慢SQL记录
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true

###可以手动配置也可以使用默认配置
  freemarker:
    allow-request-override: false
    cache: false
    charset: UTF-8
    content-type: text/html; charset=utf-8
    suffix: .ftl
    template-loader-path: classpath:/templates
eureka:
  client:
    service-url:
    ##### 当前会员服务注册到eureka服务地址
       defaultZone: http://121.5.142.110:8100/eureka
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 30
# 心跳检测检测与续约时间
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2


###springcloud  feign 默认开启支持ribbon
###设置feign客户端超时时间
###默认是一秒钟超过1S 异常 java.net.SocketTimeoutException: Read timed out
ribbon:
###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
 ReadTimeout: 5000
###指的是建立连接后从服务器读取到可用资源所用的时间。
 ConnectTimeout: 5000

#####开启hystrix
 feign:
  hystrix:
   enabled: true
system:
  #####0 不使用  1使用 [存放日志]
  isElasticsearch: 0
  ###elasticsearch的服务器地址
  elasticsearchHost: 121.5.142.110
  ####通过http请求的端口号是9200，通过客户端请求的端口号是9300
  elasticsearchPort: 9300
  ###设置es集群名称
  clusterName: my-application