server:
  port: 8700
###服务别名----服务注册到注册中心名称 
spring:
  application:
    name: app-soft-platform
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.0.110:1521:zhlis
#    username: bslis
#    password: bsoft
#测试服务器 地址
    url: jdbc:oracle:thin:@192.168.0.109:1521:orcl2
    username: zhlis
    password: zhlis
#测试服务器 地址
#    url: jdbc:oracle:thin:@192.168.100.2:1521:jbzyydb
#    username: zhlis
#    password: yhb6sqtZhlis

# 正式库数据库   password: yhb6sqtZhlis
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
    ##### 当前会员服务注册到eureka服务地址
#       defaultZone: http://localhost:8100/eureka
#云服务上 eureka地址
       defaultZone: http://121.5.142.110:8100/eureka
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 30
# 心跳检测检测与续约时间
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2


###springcloud  feign 默认开启支持ribbon
###设置feign客户端超时时间
###默认是一秒钟超过1S 异常 java.net.SocketTimeoutException: Read timed out
ribbon:
###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
 ReadTimeout: 50000
###指的是建立连接后从服务器读取到可用资源所用的时间。
 ConnectTimeout: 50000

#####开启hystrix
 feign:
  hystrix:
   enabled: true
##广安DRGS前1-13接口使用ipAddr端口是8090 14-15使用ipAddr2是8998
drgs:
  ipAddr: 10.164.45.249:8090
  ipAddr2: 10.164.45.249:8998
  ##########下面参数达州DRGS使用##############
  userId: 8BA78A4E1B20157957C41572E8E724AD
  ######siginMethod 1：简单的安全校验 2：复杂的安全校验########
  siginMethod: 2
  token: CCEDEA8B45AC160AB51AF0987126BD49
  ####国新健康医保平台地址
  urlAddr: http://192.192.74.90:86/MedicalServiceJson
  ####获取数据的地址
  odinAddr: http://172.30.51.115:7232/drgs?wsdl
  odinNameSpace: http://www.bsoft.drgs.com
  odinMethod: operationRequest
  hospitalID: 021001

system:
  #####0 不使用  1使用 [存放日志]
  isElasticsearch: 0
  ###elasticsearch的服务器地址
  elasticsearchHost: 127.0.0.1
  ####通过http请求的端口号是9200，通过客户端请求的端口号是9300
  elasticsearchPort: 9300
  ###设置es集群名称
  clusterName: my-application
### 定时器配置内容
diantime:
  corn1: 0 0/60 * * * ?
#  corn1: 0 */10 * * * *
dian:
  url: http://report.dalabs.cn/RasClientDetail.asmx?wsdl
  clientid: 重庆市江北区中医院
  clientguid: D8D0324B48ABA40BE040A8C02A000627
  method1: GetDetailData6
  method2: